### ISSUE TITLE
get username failed by the process id, err: user: unknown userid

### ISSUE THREAD

**Issue by ygxxii** [chaosblade-io/chaosblade#1038]
## Issue Description

Type: *bug report*

### Describe what happened (or what feature you want)

JVM experiments drill failed. Run following commands got error in container (Kubernetes Pod):

```bash
./blade prepare jvm --pid 1
{"code":63014,"success":false,"error":"`1`: get username failed by the process id, err: user: unknown userid 1000","result":"cdff374fa5e330be"}
```

```bash
./blade create jvm OutOfMemoryError --pid 1 --area HEAP
{"code":63014,"success":false,"error":"`1`: get username failed by the process id, err: user: unknown userid 1000","result":"3f8f49aeac1f5347"}
```

### Describe what you expected to happen

JVM experiments drill succeed.

### How to reproduce it (as minimally and precisely as possible)

1. Dockerfile (do not create user that userid=1000):

```Dockerfile
FROM eclipse-temurin:8-jdk-centos7
RUN mkdir /opt/app
COPY math-game.jar /opt/app
CMD ["java", "-jar", "/opt/app/math-game.jar"]
```

> `math-game.jar` is from[ Arthas](https://github.com/alibaba/arthas/tree/master/math-game).

2. Deployment.yaml (**NOTE** runAsUser):

```yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: math-game
spec:
  selector:
    matchLabels:
      app: math-game
  template:
    metadata:
      labels:
        app: math-game
    spec:
      containers:
        - name: math-game
          image: <image-url>
          command: ["java"]
          args: ["-jar","/opt/app/math-game.jar"]
          resources:
            limits:
              cpu: "1"
              memory: 100Mi
            requests:
              cpu: 200m
              memory: 20Mi
      securityContext:
        fsGroup: 1000
        runAsGroup: 1000
        runAsUser: 1000
```

3. `kubectl exec` login to container ;

4. Change current dir to somewhere can write. e.g. `/var/tmp`:

```bash
cd /var/tmp
```

5. Download and unpack ChaosBlade CLI: 

```bash
wget https://github.com/chaosblade-io/chaosblade/releases/download/v1.7.3/chaosblade-1.7.3-linux-amd64.tar.gz -O chaos.tar.gz && tar -zxvf chaos.tar.gz
```

6. Run ChaosBlade CLI:

```bash
./blade prepare jvm --pid 1
```

### Tell us your environment

Kubernetes: 1.28.9-aliyun.1
Worker Node: Alibaba Cloud Linux 3.2104 LTS 64-bit

### Anything else we need to know?

ChaosBlade use [os/user]( https://github.com/chaosblade-io/chaosblade/blob/a6edf881e90f194bcff5f4897f54dc1095a31cc1/exec/jvm/sandbox.go#L103) to get current user's username. So I tested following code in this container:

```go
package main

import (
   "fmt"
   "log"
   "os/user"
)

func main() {
   currentUser, err := user.Current()
   if err != nil {
      log.Fatalf(err.Error())
   }

   name := currentUser.Name
   id := currentUser.Uid
   username := currentUser.Username

   fmt.Printf("Username is: %s\n", username)
   fmt.Printf("name is: %s\n", name)
   fmt.Printf("id is: %s\n", id)
}
```

Got a same error:

```log
user: unknown userid 1000
```
