### ISSUE TITLE
node-process kill ignore-not-found error : command exec failed, exit status 2

### ISSUE THREAD

**Issue by znadm** [chaosblade-io/chaosblade#1119]
# Issue Description
Type: bug report or feature request

## Describe what happened (or what feature you want)

<img width="1432" alt="Image" src="https://github.com/user-attachments/assets/656d40bd-31dd-4ce6-9adb-8bfae08a4046" />

## Describe what you expected to happen
even if the process does not exist, it can still execute successfully
```yaml
  - name: ignore-not-found
    desc: Ignore process that cannot be found
    noArgs: true
    required: false
    requiredWhenDestroyed: false
```

## How to reproduce it (as minimally and precisely as possible)
```shell
blade create k8s node-process kill --process top --signal 9 --ignore-not-found --names master --kubeconfig ~/.kube/config
```

## Tell us your environment
- linux-OpenCloudOS 8.8
- Docker version 20.10.24, build 297e128
- k8s v1.20.11
- chaosblade 1.7.4

Anything else we need to know?
