### ISSUE TITLE
pod operator doesnt tolerate the node taint  so the opeator pod pending

### ISSUE THREAD

**Issue by fakerpawnno1** [chaosblade-io/chaosblade#1179]
![20230926172121](https://github.com/chaosblade-io/chaosblade/assets/16134393/669d4216-98b0-4c39-b8a5-c71c80610b2b)

**Comment by oss-sentinel-ai** [comment]
**Issue Evaluation**

Category: `type/bug` | Status: **Confirmed** | Severity: **Low**

The `chaosblade-operator` pod goes into `Pending` state because it doesn't tolerate node taints, preventing scheduling on tainted nodes (e.g., control-plane nodes, GPU nodes, or nodes with custom taints).

**Root Cause:** The Helm chart's operator Deployment doesn't include tolerations for common node taints like:
- `node-role.kubernetes.io/master:NoSchedule`
- `node-role.kubernetes.io/control-plane:NoSchedule`
- Custom taints on dedicated nodes

**Fix:** Add configurable tolerations to the Helm chart:
```yaml
# values.yaml
tolerations:
  - key: "node-role.kubernetes.io/master"
    operator: "Exists"
    effect: "NoSchedule"
  - key: "node-role.kubernetes.io/control-plane"
    operator: "Exists"
    effect: "NoSchedule"
```

**Affected Component:** `chaosblade-operator/deploy/helm/chaosblade-operator/templates/deployment.yaml`

**Note:** This is related to #1281 (chaosblade-tool DaemonSet also needs tolerations). Both the operator Deployment and tool DaemonSet should have configurable tolerations.

**Recommendation:** This is a straightforward Helm chart fix. Consider also adding `nodeSelector` and `affinity` configurations for flexible scheduling.

---
*Automated evaluation by [oss-taishan-ai](https://github.com/oss-taishan-ai) - ChaosBlade Community Bot*
