### ISSUE TITLE
How to set parameter 'image-repo' when blade creates k8s container network?

### ISSUE THREAD

**Issue by LouisSum** [chaosblade-io/chaosblade#269]
### Description
**environment: k8s cluster**

I encountered a problem when I was trying to conduct the single container network loss experiment.  My yaml is as follows:
```yaml
apiVersion: chaosblade.io/v1alpha1
kind: ChaosBlade
metadata:
  name: container-network-loss
spec:
  experiments:
  - scope: container
    target: network
    action: loss
    desc: "container network loss"
    matchers:
    - name: interface
      value:
      - "eth0"
    - name: container-ids
      value:
      - "4566f1w67667"
    - name: names
      value:
      - "test"
    - name: image-repo
      value:
      - "registry.abc.com/chaosblade/chaosblade-tool:0.4.0"
    - name: namespace
      value:
      - "default"
    - name: percent
      value:
      - "100"
```
Actually, I didn't set the  'image-repo' at the begnning, but there would be an error:
```yaml
"status": {
        "expStatuses": [
            {
                "action": "loss",
                "error": "see resStatus for the error details",
                "resStatuses": [
                    {
                        "error": "Error response from daemon: Get https://registry.cn-hangzhou.aliyuncs.com/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)",
                        "kind": "container",
```

The reason is that I cannot connect aliyuncs registory through the intranet, so I add the params 'image-repo', as shown above. **However**, it still didn't work.

**Finally**, I solved the problem and share with you now.
