### ISSUE TITLE
 Does the software support random killing of k8s pods and other operations

### ISSUE THREAD

**Issue by quanwenqi2** [chaosblade-io/chaosblade#326]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)
chaosblade是一款覆盖面很广的故障注入测试工具，因此我希望引入此软件对 K8s Paas平台进行测试，但是发现只能针对特定的pod进行故障注入（delete pod或者pod cpu负载等），没有其他针对Paas 的chaos工具（Powerfulseal、Chaos-mesh等）拥有在规定时间内随机等delete 规定分区下的pod，这样就软件就缺少了部分随机性。
如Chaos-mesh的每隔一分钟随机删除default分区下标签为chaos:test的pod
```
apiVersion: pingcap.com/v1alpha1
kind: PodChaos
metadata:
  name: pod-kill-example
  namespace: chaos-testing
spec:
  action: pod-kill
  mode: one
  selector:
    namespaces:
      - default
    labelSelectors:
      "chaos": "test"
  scheduler:
    cron: "@every 1m"
```
因此chaosblade是否有打算引入以上随机功能（规定时间范围内，随机的针对节点、服务进行故障注入）？

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.
