### ISSUE TITLE
Support execution policy for chaosblade operator

### ISSUE THREAD

**Issue by xcaspar** [chaosblade-io/chaosblade#354]
Chaosblade-operator is a chaos engineering experimental project for cloud-native systems. It supports a wide range of cloud-native experimental scenarios. You can use blade command or kubectl to execute yaml files, see [usage documentation] ( https://chaosblade-io.gitbook.io/chaosblade-help-zh-cn/blade-create-k8s ), the experimental scenes all follow [chaos experimental model] ( https://github.com/chaosblade-io/chaosblade/wiki/%E6%B7%B7%E6%B2%8C%E5%AE%9E%E9%AA%8C%E6%A8%A1%E5%9E%8B ), you can easily use and expand the experimental scenario.

The current problem is that there is a lack of execution policies for experimental scenarios. For example, you can configure execution at nine o'clock A.M. every Wednesday.

This topic is intended to provide a set of chaotic experiment execution policies. You can use blade to execute by adding execution policy parameters, or configure kubectl to perform in the yaml file of the experiment. The following requirements must be met:
1. Do not destroy the original experimental scenario model, and add the execution policy configuration.
2. The execution strategy must meet the specified month, week, day, hour, and minute time configurations at least.

Related issue: #353

**Comment by oss-sentinel-ai** [comment]
**Issue Evaluation**

Category: `type/feature` | Status: **Evaluated** | `AliSoC2020` | Component: `chaosblade-operator`

Feature request to support execution policies for the ChaosBlade operator, such as:
- Scheduled execution (cron-based)
- Conditional execution (based on metrics)
- Approval workflows

**Proposed Features:**
```yaml
apiVersion: chaosblade.io/v1alpha1
kind: ChaosBlade
metadata:
  name: scheduled-cpu
spec:
  policy:
    schedule: "0 2 * * *"  # Run at 2 AM daily
    duration: 30m           # Auto-destroy after 30 minutes
    approval: false         # No manual approval needed
  experiments:
  - scope: pod
    target: cpu
    action: fullload
    matchers:
    - name: cpu-percent
      value: ["80"]
```

**Related:** #451 (sub-minute scheduling), #322 (visual service)

---
*Automated evaluation by [oss-taishan-ai](https://github.com/oss-taishan-ai) - ChaosBlade Community Bot*
