### ISSUE TITLE
use chaosblade cli in k3s unauthorized

### ISSUE THREAD

**Issue by tsingloon** [chaosblade-io/chaosblade#364]
{
    "code": 200,
    "success": true,
    "result": {
        "Uid": "f96dc7dc66ab89c6",
        "Command": "k8s",
        "SubCommand": "node-cpu fullload",
        "Flag": " --debug=true --cpu-percent=30 --timeout=100",
        "Status": "Error",
        "Error": "Unauthorized",
        "CreateTime": "2020-05-29T16:42:03.428549517+08:00",
        "UpdateTime": "2020-05-29T16:42:04.871559278+08:00"
    }
}

add --debug for no more chaosblade logs
just "time="2020-05-29T16:42:03.458627989+08:00" level=info msg="create uid: f96dc7dc66ab89c6, target: cpu, scope: node, action: fullload""

**Comment by xcaspar** [comment]
Please enable chaosblade-operator debug log.
```
kubectl edit deploy chaosblade-operator -n XXX
```
Add `--webhook-enable` in chaosblade-operator container args. Wait for updating and then use the following command to see logs.
```
kubectl logs -f chaosblade-operator-XXX -n XXX
```
Re-execute blade create command.

**Comment by sunny0826** [comment]
k3s 默认的 runtime 是 containerd，部分基于 docker 的功能是不可用的

**Comment by oss-sentinel-ai** [comment]
**Issue Evaluation**

Category: `type/bug` | Status: **Answered**

ChaosBlade CLI returns `unauthorized` error when running experiments in K3s.

**Root Cause:** The CLI needs proper RBAC permissions to create experiments. In K3s, the default service account may not have the required permissions.

**Solution:**
1. **Create RBAC for ChaosBlade:**
   ```yaml
   apiVersion: rbac.authorization.k8s.io/v1
   kind: ClusterRole
   metadata:
     name: chaosblade-role
   rules:
   - apiGroups: ["chaosblade.io"]
     resources: ["chaosblades"]
     verbs: ["*"]
   - apiGroups: [""]
     resources: ["pods", "nodes"]
     verbs: ["get", "list", "watch"]
   ---
   apiVersion: rbac.authorization.k8s.io/v1
   kind: ClusterRoleBinding
   metadata:
     name: chaosblade-binding
   subjects:
   - kind: ServiceAccount
     name: default
     namespace: default
   roleRef:
     kind: ClusterRole
     name: chaosblade-role
     apiGroup: rbac.authorization.k8s.io
   ```

2. **Or use the operator** which handles RBAC automatically.

---
*Automated evaluation by [oss-taishan-ai](https://github.com/oss-taishan-ai) - ChaosBlade Community Bot*
