### ISSUE TITLE
The problem of executing a network scenario in the container

### ISSUE THREAD

**Issue by tiny-x** [chaosblade-io/chaosblade#430]
# Issue Description
bug report

### Describe what happened (or what feature you want)
exec command
````
./blade destroy docker network loss --image-version=0.7.0 --image-repo=registry.cn-hangzhou.aliyuncs.com/chaosblade/chaosblade-tool --container-id=54d9e2fc09d541bfb35b8eb1380fdd2f0928292e10867f0c70ebbac81025a1fc --interface=eth0 --percent=100 --remote-port=80
````
The returned JSON message cannot be parsed

or
container-network-by-id.yaml
````yaml
apiVersion: chaosblade.io/v1alpha1
kind: ChaosBlade
metadata:
  name: container-network-by-id
spec:
  experiments:
  - scope: container
    target: network
    action: loss
    desc: "container network by id"
    matchers:
    - name: container-names
      value: ["tomcat"]
      # pod names
    - name: names
      value: ["tomcat-test"]
    - name: percent
      value: ["100"]
    - name: interface
      value: ["eth0"]
    - name: local-port
      value: ["80"]
````
````
kubectl apply -f container-network-by-id.yaml
````
Exec `kubectl delete` is blocking

````
kubectl delete -f container-network-by-id.yaml
````
