### ISSUE TITLE
How about if the ChaosBlade support userdefine fault , that will make greate meaningful.

### ISSUE THREAD

**Issue by gotoworld** [chaosblade-io/chaosblade#446]
## feature request

How about if the ChaosBlade support userdefine fault , that will make greate meaningful.

As we know, ChaosBlade will not cover all fault case, so why not define a type os Action support userdefine fault.

Thanks.

**Comment by gotoworld** [comment]
With a open chaos experimental models, then user can make a accident as a ChaosBlade Experiment.

**Comment by xcaspar** [comment]
@gotoworld Now experiments will be categorized, such as os, docker, kubernetes, etc., user-defined experiments should also belong to a category, can you give a special experiment example?

**Comment by oss-sentinel-ai** [comment]
**Issue Evaluation**

Category: `type/feature` | Status: **Evaluated**

Feature request for user-defined fault injection — allowing users to define custom chaos experiments beyond the built-in ones.

**Status (from @xcaspar):** User-defined experiments should belong to a category. The `script` executor already provides a way to run custom experiments.

**Current Support:**
1. **Script Executor:**
   ```bash
   blade create script exit --script-path /path/to/fault.sh
   ```

2. **Custom Experiment Framework (chaosblade-exec-custom):**
   Users can create custom experiment plugins by implementing the experiment model interface.

3. **ChaosBlade Box Custom Plugins:**
   Register custom experiments in the Box platform for web-based management.

**Example Custom Experiment:**
```yaml
# custom-experiment.yaml
kind: Experiment
metadata:
  name: custom-db-fault
  categories: ["database"]
spec:
  scope: host
  target: custom-db
  actions:
    - name: pool-exhaust
      desc: "Exhaust database connection pool"
      flags:
        - name: max-connections
          desc: "Target max connections"
          type: int
          default: 1
```

**Related:** #448 (shell script execution), #828 (custom experiment framework)

---
*Automated evaluation by [oss-taishan-ai](https://github.com/oss-taishan-ai) - ChaosBlade Community Bot*
