### ISSUE TITLE
chaosblade如何对容器应用生效,比如模拟程序异常.

### ISSUE THREAD

**Issue by 928234269** [chaosblade-io/chaosblade#455]
## Issue Description

Type: *bug report* , *feature request* or *question*

### Describe what happened (or what feature you want)
我的跑在k8s的容器里,我想对容器里的应用进行异常注入,目前的想法是把blade文件挂在到容器内使用,请问有其他好的方式.

My application is in the container of K8s, and I want to inject the application in the container with exception. At present, My idea is to hang the blade file in the container for use. May I ask if there are other good ways?
### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by xcaspar** [comment]
@928234269 从0.7.0 版本就支持了K8s 下 Java 应用演练，请下载使用最新的版本.

**Comment by oss-sentinel-ai** [comment]
**Issue Evaluation**

Category: `type/question` | Status: **Answered**

Question: How to inject exceptions into container applications (e.g., simulate program exceptions)?

**Answer (from @xcaspar):** ChaosBlade has supported K8s Java application experiments since v0.7.0. Use the latest version for best results.

**K8s JVM Experiment:**
```yaml
apiVersion: chaosblade.io/v1alpha1
kind: ChaosBlade
metadata:
  name: jvm-exception
spec:
  experiments:
  - scope: pod
    target: jvm
    action: throwCustomException
    desc: "throw exception"
    matchers:
    - name: classname
      value: ["com.example.MyService"]
    - name: methodname
      value: ["processOrder"]
    - name: exception
      value: ["java.lang.RuntimeException"]
    - name: names
      value: ["my-app-pod"]
    - name: namespace
      value: ["default"]
```

**Direct CLI (inside container):**
```bash
# Enter the container
kubectl exec -it <pod> -- /bin/sh

# Mount JVM agent
blade prepare jvm --process <java-process-name>

# Inject exception
blade create jvm throwCustomException   --classname com.example.MyService   --methodname processOrder   --exception java.lang.RuntimeException
```

**Related:** #450 (RPC/Mybatis injection), #671 (K8s JVM)

---
*Automated evaluation by [oss-taishan-ai](https://github.com/oss-taishan-ai) - ChaosBlade Community Bot*
