### ISSUE TITLE
container-process kill/stop  failed

### ISSUE THREAD

**Issue by tomknocks3154** [chaosblade-io/chaosblade#461]
## Issue Description
In a istio container, process kill/stop didn't work.
Type: *bug report*

### Describe what happened (or what feature you want)
how yaml file defined
`---
apiVersion: chaosblade.io/v1alpha1
kind: ChaosBlade
metadata:
  name: process-kill
spec:
  experiments:
  - scope: container
    target: process
    action: kill
    desc: "process-kill"
    matchers:
    - name: labels
      value:
      - "app.kubernetes.io/name=cloud"
    - name: namespace
      value:
      - "cloud"
    - name: container-names
      value:
      - "istio-proxy"
    - name: pid
      value:
      - "20"`

1.experiment is successful and running
2.envoy process is still working
3.istio-proxy container didn't force exit

### Describe what you expected to happen
1.it maybe better if the secnario results "kill -9 PID" and exit.

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by xcaspar** [comment]
The container may be unable to respond to the KILL signal. You can try to use the `signal parameter. The parameter value is 15.

**Comment by oss-sentinel-ai** [comment]
**Issue Evaluation**

Category: `type/question` | Status: **Answered**

Container process kill/stop experiment fails in an Istio-enabled container.

**Root Cause (from @xcaspar):** The container process may not respond to the default `SIGKILL` (signal 9) signal. In Istio environments, the sidecar proxy or application may handle signals differently.

**Solution:**
```yaml
# Use SIGTERM (signal 15) instead of SIGKILL
apiVersion: chaosblade.io/v1alpha1
kind: ChaosBlade
metadata:
  name: process-kill
spec:
  experiments:
  - scope: container
    target: process
    action: kill
    desc: "kill process"
    matchers:
    - name: process
      value: ["pilot-agent"]
    - name: signal
      value: ["15"]
    - name: container-names
      value: ["istio-proxy"]
```

**Note for Istio:**
- `istio-proxy` (Envoy) handles SIGTERM gracefully
- `pilot-agent` handles SIGTERM by shutting down the proxy
- Using SIGKILL on `pilot-agent` may cause immediate restart

**Related:** #670 (process stop), #668 (process kill in K8s)

---
*Automated evaluation by [oss-taishan-ai](https://github.com/oss-taishan-ai) - ChaosBlade Community Bot*
