### ISSUE TITLE
Expose the chaosblade-tool daemonset configuration

### ISSUE THREAD

**Issue by xcaspar** [chaosblade-io/chaosblade#527]
## Issue Description

Type: *feature request*

### Describe what happened (or what feature you want)
Now the daemonset deployment is controlled through the `daemonset.enable` switch. Although it is easy to open, but the daemonset cann't be configured.

### Describe what you expected to happen
Expose the chaosblade-tool daemonset yaml deployment file. 

### How to reproduce it (as minimally and precisely as possible)

1. 
2. 
3.

**Comment by oss-sentinel-ai** [comment]
**Issue Evaluation**

Category: `type/feature` | Status: **Evaluated** | Priority: **Medium** | Component: `chaosblade-operator`

Feature request to expose the `chaosblade-tool` DaemonSet configuration for customization.

**Current State:** The DaemonSet configuration is hardcoded in the operator, limiting:
1. Resource limits/requests customization
2. Node selector/toleration configuration
3. Security context adjustments
4. Image pull secrets for private registries

**Proposed Enhancement:**
1. **Helm values:** Add configurable parameters:
   ```yaml
   daemonset:
     resources:
       limits:
         cpu: "500m"
         memory: "512Mi"
     nodeSelector:
       node-role.kubernetes.io/worker: ""
     tolerations:
       - key: "node-role.kubernetes.io/master"
         effect: "NoSchedule"
     imagePullSecrets:
       - name: my-registry-secret
   ```

2. **CRD-level overrides:** Allow per-experiment DaemonSet customization via the ChaosBlade CR

**Use Cases:**
- Large clusters: Increase DaemonSet resource limits
- Multi-zone clusters: Schedule Daemonset on specific node pools
- Air-gapped environments: Use private image registries

**Related:** #585 (DaemonsetEnable parameter), #536 (auto-install missing commands)

---
*Automated evaluation by [oss-taishan-ai](https://github.com/oss-taishan-ai) - ChaosBlade Community Bot*
