### ISSUE TITLE
executor network loss in experiments of k8s pod-network, prompt ‘RTNETLINK answers: Operation not permitted\n exit status 2 exit status 1"’

### ISSUE THREAD

**Issue by lss9981** [chaosblade-io/chaosblade#665]
k8s环境没有变化，只是将chaosblade-operaotr从1.3.0升级到1.5.0
在1.3.0 网络场景注入没问题，但是到1.5.0报错，
k8s服务 启动时添加 --priveleged 或 --cap-add=NET_ADMIN 参数，则注入成功。
有没有办法可以做到不改启动参数的办法
1. 
2. 
3. 

### Tell us your environment
![image](https://user-images.githubusercontent.com/42905828/155494963-f877a7ed-d003-4558-8361-42c30e2cb01d.png)

![image](https://user-images.githubusercontent.com/42905828/155494891-34326110-0c3b-4d4e-a688-4a085707b815.png)

**Comment by lss9981** [comment]
[https://github.com/chaosblade-io/chaosblade/issues/226](url)

**Comment by xcaspar** [comment]
You can use `use-sidecar-container-network` flag to resolve it.

**Comment by oss-sentinel-ai** [comment]
**Issue Evaluation**

Category: `type/question` | Status: **Answered**

After upgrading from chaosblade-operator v1.3.0 to v1.5.0, network loss experiments fail with `RTNETLINK answers: Operation not permitted`.

**Root Cause:** In v1.5.0, the network experiment execution model changed. The `tc` commands now run inside the target container's network namespace instead of the chaosblade-tool pod's namespace. This requires the target container to have `NET_ADMIN` capability.

**Solution (from @xcaspar):** Use the `--use-sidecar-container-network` flag to run network experiments in the sidecar container's network namespace (which has the required capabilities):

```yaml
spec:
  experiments:
  - scope: container
    target: network
    action: loss
    matchers:
    - name: names
      value: ["<pod-name>"]
    - name: namespace
      value: ["<ns>"]
    - name: use-sidecar-container-network
      value: ["true"]
```

**Why the change:** In v1.3.0, network experiments ran in the tool pod's namespace, which had `--privileged`. In v1.5.0, the execution moved to the target container for more accurate network simulation, but this requires the target to have `NET_ADMIN`.

**Trade-off:**
- Without `--use-sidecar-container-network`: More accurate (affects only the target container's traffic), but requires `NET_ADMIN`
- With `--use-sidecar-container-network`: Works without modifying pod security, but affects the entire pod's network

**Related:** #672 (tc not installed), #716 (root required for network experiments)

---
*Automated evaluation by [oss-taishan-ai](https://github.com/oss-taishan-ai) - ChaosBlade Community Bot*
