### ISSUE TITLE
GitHub action for CICD

### ISSUE THREAD

**Issue by MandssS** [chaosblade-io/chaosblade#793]
## Issue Description

Need add workflows for github action, models is:

- [ ] [chaosblade-exec-os](https://github.com/chaosblade-io/chaosblad/chaosblade-exec-os)
- [ ] [chaosblade-exec-cri](https://github.com/chaosblade-io/chaosblad/chaosblade-exec-cri)
- [ ] [chaosblade-operator](https://github.com/chaosblade-io/chaosblad/chaosblade-operator)
- [ ] [chaosblade](https://github.com/chaosblade-io/chaosblad/chaosblade)

### How to reproduce it (as minimally and precisely as possible)

1. 
5. 
6.

**Comment by oss-sentinel-ai** [comment]
**Issue Evaluation**

Category: `type/enhancement` | Status: **Evaluated** | Priority: **Medium**

Feature request to add GitHub Actions CI/CD workflows for multiple ChaosBlade repositories:
- `chaosblade-exec-os`
- `chaosblade-exec-cri`
- `chaosblade-operator`
- `chaosblade` (main)

**Assessment:** Adding CI/CD pipelines is essential for maintaining code quality and release reliability.

**Recommended Workflow Structure:**
1. **PR Check:** Run `go vet`, `go build`, and unit tests on every PR
2. **Release Build:** On tag push, build binaries for linux/amd64 and linux/arm64
3. **Image Push:** Build and push Docker images to a registry
4. **Lint:** Run `golangci-lint` for code quality checks

**Example GitHub Actions YAML:**
```yaml
name: CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '1.18'
      - run: go vet ./...
      - run: go build ./...
      - run: go test ./...
```

**Affected Repositories:** All core ChaosBlade Go repositories

**Recommendation:** Start with the main `chaosblade` repository as a template, then replicate to other repos. Consider using a reusable workflow to avoid duplication.

---
*Automated evaluation by [oss-taishan-ai](https://github.com/oss-taishan-ai) - ChaosBlade Community Bot*
