### ISSUE TITLE
如何权限控制

### ISSUE THREAD

**Issue by openstack-test** [chaosblade-io/chaosblade#810]
请问，社区对权限控制方面有什么好的办法或建议吗？具体而言，即如何控制某个用户只能对pod、容器资源执行故障演练，不能对节点资源执行故障演练。退一步，如何管理控制所有用户不能对节点执行故障注入。

**Comment by Yuaninga** [comment]
可以自己增加下关于casbin的插件在控制页面上权限控制。

**Comment by oss-sentinel-ai** [comment]
**Issue Evaluation**

Category: `type/question` | Status: **Answered**

The user asks about permission control in ChaosBlade — specifically, how to restrict users to only perform pod/container experiments and prevent node-level experiments, or block experiments on specific namespaces (like `kube-system`).

**Current State:** ChaosBlade itself does not have built-in RBAC (Role-Based Access Control). Permission control relies on:

**1. Kubernetes RBAC (for operator-based experiments):**
```yaml
# Restrict ChaosBlade CR creation to specific namespaces
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: chaosblade-user
  namespace: default  # Only allow in 'default' namespace
rules:
- apiGroups: ["chaosblade.io"]
  resources: ["chaosblades"]
  verbs: ["create", "get", "list", "watch", "delete"]
```

**2. OPA/Gatekeeper (for policy enforcement):**
```yaml
# Deny ChaosBlade CRs targeting kube-system namespace
apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sdenychoasbladenamespace
spec:
  crd:
    spec:
      names:
        kind: K8sDenyChaosbladeNamespace
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sdenychaosbladenamespace
        deny[msg] {
          input.review.object.spec.namespace == "kube-system"
          msg := "ChaosBlade experiments on kube-system are not allowed"
        }
```

**3. Casbin (for ChaosBlade Box, as suggested by @Yuaninga):**
Integrate casbin into the Box web UI for fine-grained permission control.

**Recommendation:** For production use, combine K8s RBAC (namespace restriction) with OPA/Gatekeeper (resource-type restriction) for defense in depth.

---
*Automated evaluation by [oss-taishan-ai](https://github.com/oss-taishan-ai) - ChaosBlade Community Bot*
